services:
  frontend-container:
    container_name: frontend-container
    build:
      context: ./Pools-App-Frontend
    ports:
      - "4200:4200"
    networks:
      - mongo-network
    depends_on:
      - backend-container

  backend-container:
    container_name: backend-container
    build:
      context: ./Pools-App-Backend
    ports:
      - "1234:1234"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-container:27017
      - ME_CONFIG_MONGODB_DATABASE=PoolsApp
    depends_on:
      - mongo-container
    networks:
      - mongo-network

  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true
    name: mongo-network
    driver: bridge
